name: Sample Slack Workflow

on:
    pull_request:
    workflow_dispatch:

jobs:
    run_workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Create a file 
              run: openssl rand -base64 12 >> random_file.txt

            - name: Send message to slack
              id: initial-message
              uses: slackapi/slack-github-action@v1.27.0
              with:
                channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                slack-message : "Test message"
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
            
            - name: Save output to env
              id: save-output
              run: echo "INIT_MSG_TS=${{ steps.initial-message.outputs.ts }}" >> $GITHUB_ENV
            
            - name: Get file size
              run: echo "FILE_SIZE=$(stat --format=%s random_file.txt | tr -d '\n')" >> $GITHUB_ENV

            - name: Send file to slack
              run: |
                upload_url=$(curl -X POST https://slack.com/api/files.getUploadURLExternal \
                -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d '{
                        "filename": "random_file.txt",
                        "length": ${{ env.FILE_SIZE }}, // size of the file in bytes
                        "channels": "${{ secrets.SLACK_CHANNEL_ID }}"
                    }' | jq -r '.upload_url')
                echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV
            
            - name: Get env
              run: echo ${{ env }} && echo ${{ env.UPLOAD_URL }}

